# Generated by Django 5.1 on 2024-12-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mctoolApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_names', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'db_table': 'construction_tools',
            },
        ),
        migrations.CreateModel(
            name='PavingBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='image')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('construction_tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paving_breakers', to='mctoolApp.constructiontools')),
            ],
            options={
                'db_table': 'paving_breaker',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle')], max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('metric_value', models.CharField(blank=True, max_length=100, null=True)),
                ('imperial_value', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='specifications/')),
                ('paving_breaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='mctoolApp.pavingbreaker')),
            ],
            options={
                'db_table': 'Specification',
            },
        ),
        migrations.DeleteModel(
            name='pavingb',
        ),
    ]
