# Generated by Django 5.1 on 2024-12-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mctoolApp', '0002_constructiontools_pavingbreaker_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('construction_tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pro_name', to='mctoolApp.constructiontools')),
            ],
            options={
                'db_table': 'product_name',
            },
        ),
        migrations.CreateModel(
            name='Pro_SPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_spe_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pro_SPE', to='mctoolApp.pro_name')),
            ],
            options={
                'db_table': 'product_spe',
            },
        ),
    ]
