# Generated by Django 5.1 on 2024-12-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mctoolApp', '0003_pro_name_pro_spe'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('construction_tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='mctoolApp.constructiontools')),
            ],
            options={
                'db_table': 'pro',
            },
        ),
        migrations.CreateModel(
            name='spe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_spe_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spe', to='mctoolApp.pro_name')),
            ],
            options={
                'db_table': 'spe',
            },
        ),
    ]
